In [1]:
import pandas as pd
pd.set_option('display.max_columns', 500)

In [2]:
import pickle5 as pickle

file_path = './results_fe.pkl'
with open(file_path, "rb") as fh:
  results_df = pickle.load(fh)

results_df.columns = ['dataset', 'random_seed', 'train_f1_micro', 'train_f1_macro', 'train_accuracy', 'classification_report']
results_df.head()

,dataset,random_seed,train_f1_micro,train_f1_macro,train_accuracy,classification_report
0,../data/embedded_datasets/metrics_dataset.pkl,0,0.979821,0.862402,0.979821,precision recall f1-score ...
1,../data/embedded_datasets/T5_base.pkl,0,0.946188,0.740867,0.946188,precision recall f1-score ...
2,../data/embedded_datasets/T5_base_line_avg.pkl,0,0.954596,0.764286,0.954596,precision recall f1-score ...
3,../data/embedded_datasets/T5_base_line_sum.pkl,0,0.956278,0.769394,0.956278,precision recall f1-score ...
4,../data/embedded_datasets/T5_small.pkl,0,0.922646,0.689363,0.922646,precision recall f1-score ...

In [3]:
# parse dataset name
results_df.dataset = [x.split('/')[-1].split('.')[0] for x in results_df.dataset]
results_df.classification_report = [x.split() for x in results_df.classification_report]
results_df.head()

,dataset,random_seed,train_f1_micro,train_f1_macro,train_accuracy,classification_report
0,metrics_dataset,0,0.979821,0.862402,0.979821,"[precision, recall, f1-score, support, 0, 0.98..."
1,T5_base,0,0.946188,0.740867,0.946188,"[precision, recall, f1-score, support, 0, 0.98..."
2,T5_base_line_avg,0,0.954596,0.764286,0.954596,"[precision, recall, f1-score, support, 0, 0.98..."
3,T5_base_line_sum,0,0.956278,0.769394,0.956278,"[precision, recall, f1-score, support, 0, 0.98..."
4,T5_small,0,0.922646,0.689363,0.922646,"[precision, recall, f1-score, support, 0, 0.99..."

In [4]:
# parse classification report
results_df['precision_0'] = [float(x[5]) for x in results_df.classification_report]
results_df['recall_0'] = [float(x[6]) for x in results_df.classification_report]
results_df['f1_score_0'] = [float(x[7]) for x in results_df.classification_report]

results_df['precision_1'] = [float(x[10]) for x in results_df.classification_report]
results_df['recall_1'] = [float(x[11]) for x in results_df.classification_report]
results_df['f1_score_1'] = [float(x[12]) for x in results_df.classification_report]

results_df['accuracy'] = [float(x[15]) for x in results_df.classification_report]

results_df['precision_macro_avg'] = [float(x[19]) for x in results_df.classification_report]
results_df['recall_macro_avg'] = [float(x[20]) for x in results_df.classification_report]
results_df['f1_score_macro_avg'] = [float(x[21]) for x in results_df.classification_report]

results_df['precision_weighted_avg'] = [float(x[25]) for x in results_df.classification_report]
results_df['recall_weighted_avg'] = [float(x[26]) for x in results_df.classification_report]
results_df['f1_score_weighted_avg'] = [float(x[27]) for x in results_df.classification_report]

results_df.drop(columns=['classification_report'], inplace=True)

results_df.head()

,dataset,random_seed,train_f1_micro,train_f1_macro,train_accuracy,precision_0,recall_0,f1_score_0,precision_1,recall_1,f1_score_1,accuracy,precision_macro_avg,recall_macro_avg,f1_score_macro_avg,precision_weighted_avg,recall_weighted_avg,f1_score_weighted_avg
0,metrics_dataset,0,0.979821,0.862402,0.979821,0.98,0.97,0.97,0.19,0.23,0.21,0.95,0.58,0.60,0.59,0.95,0.95,0.95
1,T5_base,0,0.946188,0.740867,0.946188,0.98,0.94,0.96,0.17,0.38,0.23,0.93,0.57,0.66,0.60,0.96,0.93,0.94
2,T5_base_line_avg,0,0.954596,0.764286,0.954596,0.98,0.95,0.96,0.15,0.31,0.20,0.93,0.56,0.63,0.58,0.95,0.93,0.94
3,T5_base_line_sum,0,0.956278,0.769394,0.956278,0.98,0.95,0.96,0.19,0.38,0.25,0.93,0.58,0.67,0.61,0.96,0.93,0.94
4,T5_small,0,0.922646,0.689363,0.922646,0.99,0.93,0.96,0.18,0.54,0.27,0.92,0.58,0.73,0.62,0.96,0.92,0.94

In [5]:
results_df.to_csv('fe_final_results.csv')
results_df.to_pickle('fe_final_results.pkl')

In [6]:
results_df.describe()

,train_f1_micro,train_f1_macro,train_accuracy,precision_0,recall_0,f1_score_0,precision_1,recall_1,f1_score_1,accuracy,precision_macro_avg,recall_macro_avg,f1_score_macro_avg,precision_weighted_avg,recall_weighted_avg,f1_score_weighted_avg
count,459.000000,459.000000,459.000000,459.000000,459.000000,459.000000,459.000000,459.000000,459.000000,459.000000,459.000000,459.000000,459.000000,459.000000,459.000000,459.000000
mean,0.945950,0.742091,0.945950,0.980588,0.936732,0.957647,0.154248,0.381874,0.214444,0.919913,0.567538,0.659325,0.586035,0.956536,0.919913,0.936340
std,0.019582,0.058116,0.019582,0.005863,0.022385,0.011044,0.052601,0.167447,0.071691,0.019186,0.028033,0.077207,0.036524,0.006574,0.019186,0.011023
min,0.867152,0.577668,0.867152,0.970000,0.870000,0.920000,0.000000,0.000000,0.000000,0.860000,0.480000,0.480000,0.480000,0.940000,0.860000,0.900000
25%,0.932175,0.702388,0.932175,0.980000,0.920000,0.950000,0.120000,0.230000,0.170000,0.910000,0.550000,0.600000,0.560000,0.950000,0.910000,0.930000
50%,0.947309,0.740867,0.947309,0.980000,0.940000,0.960000,0.150000,0.380000,0.210000,0.920000,0.570000,0.660000,0.590000,0.960000,0.920000,0.940000
75%,0.960202,0.780097,0.960202,0.980000,0.950000,0.970000,0.190000,0.460000,0.260000,0.930000,0.580000,0.705000,0.610000,0.960000,0.930000,0.940000
max,0.992152,0.936570,0.992152,1.000000,0.990000,0.980000,0.360000,0.920000,0.410000,0.960000,0.670000,0.920000,0.680000,0.980000,0.960000,0.960000

In [7]:
columns = ['f1_score_1', 'precision_1', 'recall_1', 'accuracy', 'f1_score_macro_avg']

In [8]:
results_df.groupby(by=['dataset'])[columns].describe(percentiles=[])

                     f1_score_1                                        \
                          count      mean       std   min   50%   max
dataset
T5_base                    51.0  0.252941  0.059876  0.13  0.25  0.40
T5_base_line_avg           51.0  0.223137  0.077910  0.06  0.23  0.38
T5_base_line_sum           51.0  0.201765  0.064209  0.06  0.20  0.40
T5_small                   51.0  0.256275  0.059227  0.14  0.24  0.41
T5_small_line_avg          51.0  0.196078  0.072803  0.04  0.20  0.36
T5_small_line_sum          51.0  0.220784  0.054363  0.11  0.21  0.34
cubert_embedding_avg       51.0  0.169020  0.072423  0.00  0.17  0.32
cubert_embedding_sum       51.0  0.211569  0.065403  0.08  0.22  0.35
metrics_dataset            51.0  0.198431  0.075614  0.00  0.21  0.33

                     precision_1                                        \
                           count      mean       std   min   50%   max
dataset
T5_base                     51.0  0.171176  0.040331  0.09  0.17  0.26
T5_base_line_avg            51.0  0.170588  0.060080  0.05  0.18  0.29
T5_base_line_sum            51.0  0.136078  0.046047  0.05  0.13  0.28
T5_small                    51.0  0.169804  0.039623  0.10  0.17  0.26
T5_small_line_avg           51.0  0.153725  0.062768  0.03  0.14  0.36
T5_small_line_sum           51.0  0.155490  0.043049  0.07  0.15  0.28
cubert_embedding_avg        51.0  0.129412  0.058700  0.00  0.13  0.27
cubert_embedding_sum        51.0  0.144118  0.042717  0.06  0.14  0.25
metrics_dataset             51.0  0.157843  0.058798  0.00  0.15  0.28

                     recall_1                                       accuracy  \
                        count      mean       std   min   50%   max    count
dataset
T5_base                  51.0  0.502353  0.165911  0.23  0.46  0.85     51.0
T5_base_line_avg         51.0  0.339216  0.132874  0.08  0.38  0.62     51.0
T5_base_line_sum         51.0  0.405098  0.135446  0.08  0.38  0.69     51.0
T5_small                 51.0  0.546275  0.141393  0.23  0.54  0.92     51.0
T5_small_line_avg        51.0  0.288627  0.125937  0.08  0.31  0.62     51.0
T5_small_line_sum        51.0  0.397255  0.108887  0.15  0.38  0.62     51.0
cubert_embedding_avg     51.0  0.264706  0.130190  0.00  0.31  0.54     51.0
cubert_embedding_sum     51.0  0.410980  0.177519  0.15  0.38  0.85     51.0
metrics_dataset          51.0  0.282353  0.135183  0.00  0.31  0.69     51.0

                                                           f1_score_macro_avg  \
                          mean       std   min   50%   max              count
dataset
T5_base               0.913725  0.015615  0.88  0.91  0.95               51.0
T5_base_line_avg      0.931373  0.012652  0.91  0.93  0.96               51.0
T5_base_line_sum      0.905098  0.020137  0.86  0.90  0.94               51.0
T5_small              0.907451  0.017070  0.87  0.91  0.94               51.0
T5_small_line_avg     0.930196  0.015296  0.90  0.93  0.96               51.0
T5_small_line_sum     0.917255  0.016134  0.89  0.92  0.95               51.0
cubert_embedding_avg  0.925882  0.016754  0.89  0.93  0.96               51.0
cubert_embedding_sum  0.912353  0.017617  0.87  0.92  0.94               51.0
metrics_dataset       0.935882  0.012677  0.91  0.93  0.96               51.0


                          mean       std   min   50%   max
dataset
T5_base               0.602941  0.030086  0.54  0.60  0.68
T5_base_line_avg      0.594314  0.039762  0.51  0.60  0.68
T5_base_line_sum      0.575490  0.034774  0.51  0.58  0.68
T5_small              0.603333  0.031979  0.55  0.60  0.68
T5_small_line_avg     0.580000  0.037256  0.50  0.58  0.66
T5_small_line_sum     0.589020  0.030150  0.52  0.58  0.65
cubert_embedding_avg  0.564902  0.037543  0.48  0.57  0.64
cubert_embedding_sum  0.581961  0.032865  0.52  0.58  0.66
metrics_dataset       0.582353  0.037448  0.49  0.58  0.65

### Metrics

In [9]:
metrics = results_df.loc[results_df['dataset'] == 'metrics_dataset']
metrics[columns].describe(percentiles=[])

       f1_score_1  precision_1   recall_1   accuracy  f1_score_macro_avg
count   51.000000    51.000000  51.000000  51.000000           51.000000
mean     0.198431     0.157843   0.282353   0.935882            0.582353
std      0.075614     0.058798   0.135183   0.012677            0.037448
min      0.000000     0.000000   0.000000   0.910000            0.490000
50%      0.210000     0.150000   0.310000   0.930000            0.580000
max      0.330000     0.280000   0.690000   0.960000            0.650000

### T5 base

In [10]:
t5_base = results_df.loc[results_df['dataset'] == 'T5_base']
t5_base[columns].describe(percentiles=[])

       f1_score_1  precision_1   recall_1   accuracy  f1_score_macro_avg
count   51.000000    51.000000  51.000000  51.000000           51.000000
mean     0.252941     0.171176   0.502353   0.913725            0.602941
std      0.059876     0.040331   0.165911   0.015615            0.030086
min      0.130000     0.090000   0.230000   0.880000            0.540000
50%      0.250000     0.170000   0.460000   0.910000            0.600000
max      0.400000     0.260000   0.850000   0.950000            0.680000

### T5 base line avg

In [11]:
t5_base_line_avg = results_df.loc[results_df['dataset'] == 'T5_base_line_avg']
t5_base_line_avg[columns].describe(percentiles=[])

       f1_score_1  precision_1   recall_1   accuracy  f1_score_macro_avg
count   51.000000    51.000000  51.000000  51.000000           51.000000
mean     0.223137     0.170588   0.339216   0.931373            0.594314
std      0.077910     0.060080   0.132874   0.012652            0.039762
min      0.060000     0.050000   0.080000   0.910000            0.510000
50%      0.230000     0.180000   0.380000   0.930000            0.600000
max      0.380000     0.290000   0.620000   0.960000            0.680000

### T5 base line sum

In [12]:
t5_base_line_sum = results_df.loc[results_df['dataset'] == 'T5_base_line_sum']
t5_base_line_sum[columns].describe(percentiles=[])

       f1_score_1  precision_1   recall_1   accuracy  f1_score_macro_avg
count   51.000000    51.000000  51.000000  51.000000           51.000000
mean     0.201765     0.136078   0.405098   0.905098            0.575490
std      0.064209     0.046047   0.135446   0.020137            0.034774
min      0.060000     0.050000   0.080000   0.860000            0.510000
50%      0.200000     0.130000   0.380000   0.900000            0.580000
max      0.400000     0.280000   0.690000   0.940000            0.680000

### T5 small

In [13]:
t5_small = results_df.loc[results_df['dataset'] == 'T5_small']
t5_small[columns].describe(percentiles=[])

       f1_score_1  precision_1   recall_1   accuracy  f1_score_macro_avg
count   51.000000    51.000000  51.000000  51.000000           51.000000
mean     0.256275     0.169804   0.546275   0.907451            0.603333
std      0.059227     0.039623   0.141393   0.017070            0.031979
min      0.140000     0.100000   0.230000   0.870000            0.550000
50%      0.240000     0.170000   0.540000   0.910000            0.600000
max      0.410000     0.260000   0.920000   0.940000            0.680000

### T5 small line avg

In [14]:
t5_small_line_avg = results_df.loc[results_df['dataset'] == 'T5_small_line_avg']
t5_small_line_avg[columns].describe(percentiles=[])

       f1_score_1  precision_1   recall_1   accuracy  f1_score_macro_avg
count   51.000000    51.000000  51.000000  51.000000           51.000000
mean     0.196078     0.153725   0.288627   0.930196            0.580000
std      0.072803     0.062768   0.125937   0.015296            0.037256
min      0.040000     0.030000   0.080000   0.900000            0.500000
50%      0.200000     0.140000   0.310000   0.930000            0.580000
max      0.360000     0.360000   0.620000   0.960000            0.660000

### T5 small line sum

In [15]:
t5_small_line_sum = results_df.loc[results_df['dataset'] == 'T5_small_line_sum']
t5_small_line_sum[columns].describe(percentiles=[])

       f1_score_1  precision_1   recall_1   accuracy  f1_score_macro_avg
count   51.000000    51.000000  51.000000  51.000000            51.00000
mean     0.220784     0.155490   0.397255   0.917255             0.58902
std      0.054363     0.043049   0.108887   0.016134             0.03015
min      0.110000     0.070000   0.150000   0.890000             0.52000
50%      0.210000     0.150000   0.380000   0.920000             0.58000
max      0.340000     0.280000   0.620000   0.950000             0.65000

### Cubert sum

In [16]:
cubert_sum = results_df.loc[results_df['dataset'] == 'cubert_embedding_sum']
cubert_sum[columns].describe(percentiles=[])

       f1_score_1  precision_1   recall_1   accuracy  f1_score_macro_avg
count   51.000000    51.000000  51.000000  51.000000           51.000000
mean     0.211569     0.144118   0.410980   0.912353            0.581961
std      0.065403     0.042717   0.177519   0.017617            0.032865
min      0.080000     0.060000   0.150000   0.870000            0.520000
50%      0.220000     0.140000   0.380000   0.920000            0.580000
max      0.350000     0.250000   0.850000   0.940000            0.660000

### Cubert avg

In [17]:
cubert_avg = results_df.loc[results_df['dataset'] == 'cubert_embedding_avg']
cubert_avg[columns].describe(percentiles=[])

       f1_score_1  precision_1   recall_1   accuracy  f1_score_macro_avg
count   51.000000    51.000000  51.000000  51.000000           51.000000
mean     0.169020     0.129412   0.264706   0.925882            0.564902
std      0.072423     0.058700   0.130190   0.016754            0.037543
min      0.000000     0.000000   0.000000   0.890000            0.480000
50%      0.170000     0.130000   0.310000   0.930000            0.570000
max      0.320000     0.270000   0.540000   0.960000            0.640000

In [18]:
results_df.groupby(by=['dataset']).describe(percentiles=[])

                     train_f1_micro                                          \
                              count      mean       std       min       50%
dataset
T5_base                        51.0  0.934296  0.013929  0.883408  0.937780
T5_base_line_avg               51.0  0.954377  0.008733  0.932735  0.954596
T5_base_line_sum               51.0  0.933450  0.014431  0.867152  0.933857
T5_small                       51.0  0.924679  0.009787  0.905269  0.926009
T5_small_line_avg              51.0  0.957212  0.014284  0.917601  0.957960
T5_small_line_sum              51.0  0.946012  0.012091  0.906390  0.946188
cubert_embedding_avg           51.0  0.958092  0.012942  0.923206  0.960202
cubert_embedding_sum           51.0  0.941133  0.025643  0.874439  0.947870
metrics_dataset                51.0  0.964301  0.016854  0.918722  0.966928

                               train_f1_macro                                \
                           max          count      mean       std       min
dataset
T5_base               0.955157           51.0  0.714745  0.029251  0.620769
T5_base_line_avg      0.973655           51.0  0.765574  0.026332  0.709352
T5_base_line_sum      0.956278           51.0  0.712772  0.030876  0.577668
T5_small              0.944507           51.0  0.691337  0.021842  0.630838
T5_small_line_avg     0.980381           51.0  0.777635  0.042701  0.680297
T5_small_line_sum     0.972534           51.0  0.741001  0.035034  0.635770
cubert_embedding_avg  0.978139           51.0  0.768255  0.058496  0.615102
cubert_embedding_sum  0.975897           51.0  0.725291  0.076031  0.587392
metrics_dataset       0.992152           51.0  0.782208  0.083414  0.631457

                                         train_accuracy                      \
                           50%       max          count      mean       std
dataset
T5_base               0.720434  0.765971           51.0  0.934296  0.013929
T5_base_line_avg      0.764286  0.833267           51.0  0.954377  0.008733
T5_base_line_sum      0.711746  0.769394           51.0  0.933450  0.014431
T5_small              0.692514  0.736563           51.0  0.924679  0.009787
T5_small_line_avg     0.774662  0.865273           51.0  0.957212  0.014284
T5_small_line_sum     0.740867  0.828405           51.0  0.946012  0.012091
cubert_embedding_avg  0.781947  0.854025           51.0  0.958092  0.012942
cubert_embedding_sum  0.742328  0.843373           51.0  0.941133  0.025643
metrics_dataset       0.800389  0.936570           51.0  0.964301  0.016854

                                                   precision_0            \
                           min       50%       max       count      mean
dataset
T5_base               0.883408  0.937780  0.955157        51.0  0.984902
T5_base_line_avg      0.932735  0.954596  0.973655        51.0  0.979412
T5_base_line_sum      0.867152  0.933857  0.956278        51.0  0.980784
T5_small              0.905269  0.926009  0.944507        51.0  0.985686
T5_small_line_avg     0.917601  0.957960  0.980381        51.0  0.978039
T5_small_line_sum     0.906390  0.946188  0.972534        51.0  0.981176
cubert_embedding_avg  0.923206  0.960202  0.978139        51.0  0.976863
cubert_embedding_sum  0.874439  0.947870  0.975897        51.0  0.980588
metrics_dataset       0.918722  0.966928  0.992152        51.0  0.977843

                                                 recall_0                      \
                           std   min   50%   max    count      mean       std
dataset
T5_base               0.005430  0.98  0.98  1.00     51.0  0.927059  0.018793
T5_base_line_avg      0.005064  0.97  0.98  0.99     51.0  0.950000  0.013416
T5_base_line_sum      0.004401  0.97  0.98  0.99     51.0  0.920588  0.021205
T5_small              0.005746  0.98  0.99  1.00     51.0  0.918627  0.018657
T5_small_line_avg     0.005664  0.97  0.98  0.99     51.0  0.951176  0.016691
T5_small_line_sum     0.003819  0.97  0.98  0.99     51.0  0.933137  0.017831
cubert_embedding_avg  0.005095  0.97  0.98  0.99     51.0  0.945882  0.019409
cubert_embedding_sum  0.005801  0.97  0.98  0.99     51.0  0.928627  0.020593
metrics_dataset       0.005025  0.97  0.98  0.99     51.0  0.955490  0.015788

                                       f1_score_0                            \
                       min   50%   max      count      mean       std   min
dataset
T5_base               0.89  0.93  0.96       51.0  0.953922  0.008736  0.94
T5_base_line_avg      0.92  0.95  0.98       51.0  0.964510  0.007298  0.95
T5_base_line_sum      0.87  0.92  0.96       51.0  0.948824  0.011428  0.92
T5_small              0.87  0.92  0.96       51.0  0.951176  0.009305  0.93
T5_small_line_avg     0.91  0.95  0.98       51.0  0.964118  0.009204  0.94
T5_small_line_sum     0.90  0.94  0.97       51.0  0.955882  0.009628  0.94
cubert_embedding_avg  0.91  0.95  0.98       51.0  0.961176  0.010516  0.94
cubert_embedding_sum  0.88  0.93  0.97       51.0  0.953529  0.009965  0.93
metrics_dataset       0.92  0.95  0.99       51.0  0.965686  0.007551  0.95

                                 precision_1                                  \
                       50%   max       count      mean       std   min   50%
dataset
T5_base               0.95  0.97        51.0  0.171176  0.040331  0.09  0.17
T5_base_line_avg      0.97  0.98        51.0  0.170588  0.060080  0.05  0.18
T5_base_line_sum      0.95  0.97        51.0  0.136078  0.046047  0.05  0.13
T5_small              0.95  0.97        51.0  0.169804  0.039623  0.10  0.17
T5_small_line_avg     0.97  0.98        51.0  0.153725  0.062768  0.03  0.14
T5_small_line_sum     0.96  0.98        51.0  0.155490  0.043049  0.07  0.15
cubert_embedding_avg  0.96  0.98        51.0  0.129412  0.058700  0.00  0.13
cubert_embedding_sum  0.96  0.97        51.0  0.144118  0.042717  0.06  0.14
metrics_dataset       0.97  0.98        51.0  0.157843  0.058798  0.00  0.15

                           recall_1                                        \
                       max    count      mean       std   min   50%   max
dataset
T5_base               0.26     51.0  0.502353  0.165911  0.23  0.46  0.85
T5_base_line_avg      0.29     51.0  0.339216  0.132874  0.08  0.38  0.62
T5_base_line_sum      0.28     51.0  0.405098  0.135446  0.08  0.38  0.69
T5_small              0.26     51.0  0.546275  0.141393  0.23  0.54  0.92
T5_small_line_avg     0.36     51.0  0.288627  0.125937  0.08  0.31  0.62
T5_small_line_sum     0.28     51.0  0.397255  0.108887  0.15  0.38  0.62
cubert_embedding_avg  0.27     51.0  0.264706  0.130190  0.00  0.31  0.54
cubert_embedding_sum  0.25     51.0  0.410980  0.177519  0.15  0.38  0.85
metrics_dataset       0.28     51.0  0.282353  0.135183  0.00  0.31  0.69

                     f1_score_1                                        \
                          count      mean       std   min   50%   max
dataset
T5_base                    51.0  0.252941  0.059876  0.13  0.25  0.40
T5_base_line_avg           51.0  0.223137  0.077910  0.06  0.23  0.38
T5_base_line_sum           51.0  0.201765  0.064209  0.06  0.20  0.40
T5_small                   51.0  0.256275  0.059227  0.14  0.24  0.41
T5_small_line_avg          51.0  0.196078  0.072803  0.04  0.20  0.36
T5_small_line_sum          51.0  0.220784  0.054363  0.11  0.21  0.34
cubert_embedding_avg       51.0  0.169020  0.072423  0.00  0.17  0.32
cubert_embedding_sum       51.0  0.211569  0.065403  0.08  0.22  0.35
metrics_dataset            51.0  0.198431  0.075614  0.00  0.21  0.33

                     accuracy                                        \
                        count      mean       std   min   50%   max
dataset
T5_base                  51.0  0.913725  0.015615  0.88  0.91  0.95
T5_base_line_avg         51.0  0.931373  0.012652  0.91  0.93  0.96
T5_base_line_sum         51.0  0.905098  0.020137  0.86  0.90  0.94
T5_small                 51.0  0.907451  0.017070  0.87  0.91  0.94
T5_small_line_avg        51.0  0.930196  0.015296  0.90  0.93  0.96
T5_small_line_sum        51.0  0.917255  0.016134  0.89  0.92  0.95
cubert_embedding_avg     51.0  0.925882  0.016754  0.89  0.93  0.96
cubert_embedding_sum     51.0  0.912353  0.017617  0.87  0.92  0.94
metrics_dataset          51.0  0.935882  0.012677  0.91  0.93  0.96

                     precision_macro_avg                                  \
                                   count      mean       std   min   50%
dataset
T5_base                             51.0  0.577255  0.021916  0.53  0.58
T5_base_line_avg                    51.0  0.574314  0.031702  0.51  0.58
T5_base_line_sum                    51.0  0.559412  0.025172  0.51  0.56
T5_small                            51.0  0.577451  0.021803  0.54  0.57
T5_small_line_avg                   51.0  0.566667  0.032904  0.50  0.56
T5_small_line_sum                   51.0  0.568627  0.022273  0.52  0.56
cubert_embedding_avg                51.0  0.552549  0.031486  0.48  0.55
cubert_embedding_sum                51.0  0.563333  0.023721  0.52  0.56
metrics_dataset                     51.0  0.568235  0.030180  0.49  0.57

                           recall_macro_avg                                  \
                       max            count      mean       std   min   50%
dataset
T5_base               0.63             51.0  0.714706  0.078060  0.58  0.71
T5_base_line_avg      0.64             51.0  0.644510  0.064879  0.52  0.66
T5_base_line_sum      0.64             51.0  0.662745  0.064500  0.52  0.66
T5_small              0.63             51.0  0.732157  0.067419  0.58  0.73
T5_small_line_avg     0.67             51.0  0.619804  0.059883  0.50  0.62
T5_small_line_sum     0.63             51.0  0.665294  0.051395  0.55  0.67
cubert_embedding_avg  0.62             51.0  0.605490  0.060144  0.48  0.62
cubert_embedding_sum  0.62             51.0  0.669608  0.081264  0.54  0.66
metrics_dataset       0.63             51.0  0.619608  0.063780  0.49  0.63

                           f1_score_macro_avg                                  \
                       max              count      mean       std   min   50%
dataset
T5_base               0.89               51.0  0.602941  0.030086  0.54  0.60
T5_base_line_avg      0.78               51.0  0.594314  0.039762  0.51  0.60
T5_base_line_sum      0.82               51.0  0.575490  0.034774  0.51  0.58
T5_small              0.92               51.0  0.603333  0.031979  0.55  0.60
T5_small_line_avg     0.76               51.0  0.580000  0.037256  0.50  0.58
T5_small_line_sum     0.76               51.0  0.589020  0.030150  0.52  0.58
cubert_embedding_avg  0.73               51.0  0.564902  0.037543  0.48  0.57
cubert_embedding_sum  0.86               51.0  0.581961  0.032865  0.52  0.58
metrics_dataset       0.81               51.0  0.582353  0.037448  0.49  0.58

                           precision_weighted_avg                            \
                       max                  count      mean       std   min
dataset
T5_base               0.68                   51.0  0.960196  0.006779  0.95
T5_base_line_avg      0.68                   51.0  0.956471  0.005594  0.95
T5_base_line_sum      0.68                   51.0  0.956471  0.006269  0.94
T5_small              0.68                   51.0  0.961961  0.006007  0.95
T5_small_line_avg     0.66                   51.0  0.954118  0.005719  0.94
T5_small_line_sum     0.65                   51.0  0.956667  0.004761  0.95
cubert_embedding_avg  0.64                   51.0  0.952157  0.005409  0.94
cubert_embedding_sum  0.66                   51.0  0.957255  0.006349  0.95
metrics_dataset       0.65                   51.0  0.953529  0.006269  0.94

                                 recall_weighted_avg                      \
                       50%   max               count      mean       std
dataset
T5_base               0.96  0.97                51.0  0.913725  0.015615
T5_base_line_avg      0.96  0.97                51.0  0.931373  0.012652
T5_base_line_sum      0.96  0.97                51.0  0.905098  0.020137
T5_small              0.96  0.98                51.0  0.907451  0.017070
T5_small_line_avg     0.95  0.96                51.0  0.930196  0.015296
T5_small_line_sum     0.96  0.96                51.0  0.917255  0.016134
cubert_embedding_avg  0.95  0.96                51.0  0.925882  0.016754
cubert_embedding_sum  0.96  0.97                51.0  0.912353  0.017617
metrics_dataset       0.95  0.97                51.0  0.935882  0.012677

                                       f1_score_weighted_avg            \
                       min   50%   max                 count      mean
dataset
T5_base               0.88  0.91  0.95                  51.0  0.934118
T5_base_line_avg      0.91  0.93  0.96                  51.0  0.943137
T5_base_line_sum      0.86  0.90  0.94                  51.0  0.927647
T5_small              0.87  0.91  0.94                  51.0  0.930392
T5_small_line_avg     0.90  0.93  0.96                  51.0  0.941176
T5_small_line_sum     0.89  0.92  0.95                  51.0  0.934902
cubert_embedding_avg  0.89  0.93  0.96                  51.0  0.938235
cubert_embedding_sum  0.87  0.92  0.94                  51.0  0.932549
metrics_dataset       0.91  0.93  0.96                  51.0  0.944902


                           std   min   50%   max
dataset
T5_base               0.008984  0.92  0.93  0.95
T5_base_line_avg      0.007872  0.93  0.94  0.96
T5_base_line_sum      0.011931  0.90  0.93  0.95
T5_small              0.009992  0.91  0.93  0.95
T5_small_line_avg     0.009726  0.92  0.94  0.96
T5_small_line_sum     0.010074  0.92  0.94  0.96
cubert_embedding_avg  0.009530  0.92  0.94  0.96
cubert_embedding_sum  0.010362  0.91  0.93  0.95
metrics_dataset       0.007035  0.93  0.94  0.96