In [1]:
import pandas as pd
import numpy as np
import researchpy as rp

pd.set_option('display.max_columns', 500)

In [2]:
import pickle

def save_model(file_name, model):
    with open(file_name, 'wb') as file:
        pickle.dump(model, file)

In [3]:
df_feature_envy = pd.read_csv('./feature_envy.csv')
df_feature_envy.drop(columns=['method'], inplace=True)
df_feature_envy.head()

   sample_id severity
0    4256584    major
1    8922371    major
2    8653310    major
3    4734605    major
4    4514232    major

In [4]:
df_metrics = pd.read_excel('./metrics/MLCQ_FE_ck_metrics_from_project.xlsx')
df_metrics['from_project'] = np.where(df_metrics['from_project'], 1, 0)
df_metrics.head()

,constructor,line,cbo,wmc,rfc,loc,returnsQty,variablesQty,parametersQty,methodsInvokedQty,methodsInvokedLocalQty,methodsInvokedIndirectLocalQty,loopQty,comparisonsQty,tryCatchQty,parenthesizedExpsQty,stringLiteralsQty,numbersQty,assignmentsQty,mathOperationsQty,maxNestedBlocksQty,anonymousClassesQty,innerClassesQty,lambdasQty,uniqueWordsQty,modifiers,logStatementsQty,hasJavaDoc,sample_id,from_project
0,1,35,0,1,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,2,0,0,5771277,1
1,0,531,0,1,0,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,1,0,1,5788107,1
2,0,88,0,1,3,10,1,2,0,3,0,0,0,0,0,0,0,1,7,0,0,0,0,0,12,1,0,0,5788583,1
3,0,737,2,1,0,3,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51,1,0,1,5798354,1
4,1,37,0,1,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,1,0,0,5798489,1

In [5]:
df_metrics.shape

(2242, 30)

In [5]:
df_merged = pd.merge(df_feature_envy, df_metrics, how='inner')
df_merged.head()

,sample_id,severity,constructor,line,cbo,wmc,rfc,loc,returnsQty,variablesQty,parametersQty,methodsInvokedQty,methodsInvokedLocalQty,methodsInvokedIndirectLocalQty,loopQty,comparisonsQty,tryCatchQty,parenthesizedExpsQty,stringLiteralsQty,numbersQty,assignmentsQty,mathOperationsQty,maxNestedBlocksQty,anonymousClassesQty,innerClassesQty,lambdasQty,uniqueWordsQty,modifiers,logStatementsQty,hasJavaDoc,from_project
0,4256584,major,0,65,1,1,5,7,0,0,4,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,1,0,1,1
1,8922371,major,0,733,3,15,14,71,0,1,2,14,0,0,1,7,0,0,0,6,7,0,3,0,0,0,5,1,0,0,1
2,8653310,major,0,105,10,7,73,24,1,6,3,73,0,0,1,3,1,0,1,0,9,0,3,0,0,0,32,1,0,1,1
3,4734605,major,0,929,6,4,28,20,0,6,5,28,0,0,1,1,0,0,3,1,7,1,1,0,0,1,39,2,2,0,0
4,4514232,major,0,100,15,23,19,65,0,20,1,19,1,1,2,12,0,12,21,4,28,5,3,0,0,0,58,33,0,0,1

In [6]:
df_merged['label'] = np.where(df_merged.severity == 'none', 0, 1)
df_merged.head()

,sample_id,severity,constructor,line,cbo,wmc,rfc,loc,returnsQty,variablesQty,parametersQty,methodsInvokedQty,methodsInvokedLocalQty,methodsInvokedIndirectLocalQty,loopQty,comparisonsQty,tryCatchQty,parenthesizedExpsQty,stringLiteralsQty,numbersQty,assignmentsQty,mathOperationsQty,maxNestedBlocksQty,anonymousClassesQty,innerClassesQty,lambdasQty,uniqueWordsQty,modifiers,logStatementsQty,hasJavaDoc,from_project,label
0,4256584,major,0,65,1,1,5,7,0,0,4,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,1,0,1,1,1
1,8922371,major,0,733,3,15,14,71,0,1,2,14,0,0,1,7,0,0,0,6,7,0,3,0,0,0,5,1,0,0,1,1
2,8653310,major,0,105,10,7,73,24,1,6,3,73,0,0,1,3,1,0,1,0,9,0,3,0,0,0,32,1,0,1,1,1
3,4734605,major,0,929,6,4,28,20,0,6,5,28,0,0,1,1,0,0,3,1,7,1,1,0,0,1,39,2,2,0,0,1
4,4514232,major,0,100,15,23,19,65,0,20,1,19,1,1,2,12,0,12,21,4,28,5,3,0,0,0,58,33,0,0,1,1

In [7]:
rp.summary_cat(df_merged["severity"])

   Variable   Outcome  Count  Percent
0  severity      none   2176    97.06
1               minor     45     2.01
2               major     20     0.89
3            critical      1     0.04

In [8]:
df_merged.to_csv('./embedded_datasets/metrics_dataset.csv', index=False)

In [9]:
df_merged.to_pickle('./embedded_datasets/metrics_dataset.pkl')